### ISSUE TITLE
Make the processor independent of changeset_id

### ISSUE THREAD

**Issue by geohacker** [mapbox/tile-reduce-peer-review#1]
Hey @Rub21 - per voice, let's make this processor independent of changeset_id. How about we do this?

* Every day, filter features that are added/modified in the last 24 hours
* Then filter features that are added/modified by our team
* Then apply [rules](https://github.com/mapbox/data/issues/1515#issuecomment-160963952) and generate a GeoJSON and an mbtiles set.

cc @batpad @maning @planemad @lxbarth @mikelmaron

**Comment by Rub21** [comment]
@geohacker  sound fine !  jumping here today.

**Comment by Rub21** [comment]
### Progress
> Every day, filter features that are added/modified in the last 24 hours

Done !

> Then filter features that are added/modified by our team

Done ! [filter-users analyzer](https://github.com/mapbox/tile-reduce-peer-review/tree/processor/analyzer/filter-users)

> Then apply rules and generate a GeoJSON and an mbtiles set.

I created two analyzer for `Missing layer= to bridges` and `Untagged ways`

**Comment by geohacker** [comment]
Done.
