### ISSUE TITLE
Invalid data/corrupt mbtiles? 

### ISSUE THREAD

**Issue by geohacker** [mapbox/tile-reduce-peer-review#7]
@Rub21 and I have been running into:

```
/home/penny/tile-reduce-peer-review/node_modules/tile-reduce/node_modules/vector-tile/lib/vectortilefeature.js:81
            throw new Error('unknown command ' + cmd);
                  ^
Error: unknown command 4
    at VectorTileFeature.loadGeometry (/home/penny/tile-reduce-peer-review/node_modules/tile-reduce/node_modules/vector-tile/lib/vectortilefeature.js:81:19)
    at VectorTileFeature.toGeoJSON (/home/penny/tile-reduce-peer-review/node_modules/tile-reduce/node_modules/vector-tile/lib/vectortilefeature.js:133:23)
    at toGeoJSON (/home/penny/tile-reduce-peer-review/node_modules/tile-reduce/src/vt.js:25:36)
    at parseData (/home/penny/tile-reduce-peer-review/node_modules/tile-reduce/src/vt.js:10:32)
    at tileUnzipped (/home/penny/tile-reduce-peer-review/node_modules/tile-reduce/src/mbtiles.js:38:18)
    at Unzip.onEnd (zlib.js:167:5)
    at Unzip.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)
3254302 tiles processed in 1m 22s
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: channel closed
    at ChildProcess.target.send (child_process.js:406:26)
    at StreamArray.handleTile (/home/penny/tile-reduce-peer-review/node_modules/tile-reduce/src/index.js:115:23)
    at StreamArray.emit (events.js:95:17)
    at StreamArray.Readable.read (/home/penny/tile-reduce-peer-review/node_modules/tile-reduce/node_modules/stream-array/node_modules/readable-stream/lib/_stream_readable.js:413:10)
    at flow (/home/penny/tile-reduce-peer-review/node_modules/tile-reduce/node_modules/stream-array/node_modules/readable-stream/lib/_stream_readable.js:796:26)
    at resume_ (/home/penny/tile-reduce-peer-review/node_modules/tile-reduce/node_modules/stream-array/node_modules/readable-stream/lib/_stream_readable.js:776:3)
    at afterTick (/home/penny/tile-reduce-peer-review/node_modules/tile-reduce/node_modules/stream-array/node_modules/readable-stream/node_modules/process-nextick-args/index.js:18:8)
    at process._tickCallback (node.js:448:13)
```

I think the first forensic reports suggest corrupt mbtiles. Gotta investigate.

cc @tcql @batpad

**Comment by tcql** [comment]
@geohacker so it looks like this *might* have something to do with tile buffers - or that could be a coincidence. I don't believe not having buffers should cause you any trouble (the original osm qa tiles are bufferless), so I'm testing out a run with `-b0` added onto each of the tippecanoe commands

**Comment by tcql** [comment]
nope, still ran into some trouble :S not sure what's going on here. The source geometries that are output by the processor look good, so it's something in the process of cutting mbtiles with tippecanoe that's getting messed up. Inspecting the vector tile objects, looks like properties are good, but parsing the geometry breaks.

**Comment by ericfischer** [comment]
What version of tippecanoe are you using? Can I have a copy of one of these broken .mbtiles files to investigate?

**Comment by geohacker** [comment]
@ericfischer - https://www.dropbox.com/s/zfvkwgmt7vpvub1/changes.mbtiles?dl=0
I build tippecanoe from master, yesterday.

**Comment by geohacker** [comment]
I just built `v1.4.0` and still get the error.

**Comment by geohacker** [comment]
I'm also seeing these errors - https://gist.github.com/geohacker/ed5c9e836939afba450b

**Comment by tcql** [comment]
@ericfischer [here's a zip containing the bad mbtiles](https://github.com/mapbox/tile-reduce-peer-review/files/59450/changes.zip)

The precise tile that failed was `[ 2911, 1914, 12 ]`.

The data dumped by vector-tile-js looks like: 

```
{ _osm_node_id: 3883233313,
  _version: 1,
  _changeset: 35824904,
  _uid: 1893569,
  _user: 'sabeesh',
  _timestamp: 1449577599,
  name: 'Meenmutty Water Falls',
  tourism: 'attraction' }
{ buf: <Buffer 1a d9 02 0a 03 6f 73 6d 12 14 12 10 00 00 01 01 02 02 03 03 04 04 05 05 06 06 07 07 18 01 12 26 12 10 08 08 01 01 02 09 03 03 04 04 05 0a 09 0b 06 0c 18 ...>,
  pos: 30,
  length: 348 }
```

The actual error only occurs when you try and get the geometry

Reproducing: 

1. install tippecanoe 1.4.0
2. clone this repo
3. checkout the `faster` branch
4. npm install
5. 
```
wget -O /data/latest.planet.mbtiles.gz https://s3.amazonaws.com/mapbox/osm-qa-tiles/latest.planet.mbtiles.gz
gunzip /data/latest.planet.mbtiles.gz

BOX=[72.2900390625,10.833305983642491,80.4638671875,16.93070509876554]

# This generates the bad file
node processor/index.js --area $BOX --mbtiles /data/latest.planet.mbtiles | tippecanoe -l osm -f -o /data/changes.mbtiles -z12 -Z12 -psfk -r0

# This will blow up because it uses the bad file
node analysers/filter-users/index.js --area $BOX --mbtiles /data/changes.mbtiles | tippecanoe -l osm -f -o /data/users.mbtiles -z12 -Z12 -pscfkr -r0
```

**Comment by ericfischer** [comment]
Thanks @tcql. The interesting thing about this tile is that it contains a Point geometry that decodes as

    { "type": "Feature", "properties": { "_osm_node_id": 3.88323e+09, "_version": 1, "_changeset": 3.58249e+07, "_uid": 1.89357e+06, "_user": "sabeesh", "_timestamp": 1.44958e+09, "name": "Meenmutty Water Falls", "tourism": "attraction" }, "geometry": { "type": "MultiPoint", "coordinates": [  ] } }

It contains no points. I'm not sure how tippecanoe would ever generate an empty geometry but that must be the problem. The other feature in the tile is a reasonable-looking LineString:

    { "type": "Feature", "properties": { "_osm_way_id": 3.84969e+08, "_version": 1, "_changeset": 3.58248e+07, "_uid": 1.89357e+06, "_user": "sabeesh", "_timestamp": 1.44958e+09, "highway": "tertiary", "name": "Meenmutty Water falls" }, "geometry": { "type": "LineString", "coordinates": [ [ 75.939227, 11.675321 ], [ 75.939120, 11.675342 ], [ 75.939013, 11.675426 ], [ 75.938927, 11.675531 ], [ 75.938905, 11.675636 ], [ 75.938884, 11.675741 ] ] } }

**Comment by tcql** [comment]
@ericfischer I confirmed earlier that the input geometry is good `Point` (not an empty or anything), so it seems like something internal to tippecanoe

**Comment by ericfischer** [comment]
Looks like this may be a clipping problem. The original location is

    {"type":"Point","coordinates":[75.93921661376953,11.675494292657874]}

In the output tiles it appears in `{ "zoom": 12, "x": 2912, "y": 1914 }` as

    { "type": "Point", "coordinates": [ 75.939227, 11.675489 ] }

and then again in `{ "zoom": 12, "x": 2911, "y": 1914 }` with the missing geometry.

**Comment by ericfischer** [comment]
Thanks for finding this. Should be fixed by https://github.com/mapbox/tippecanoe/pull/124, tagged as [version 1.4.2](https://github.com/mapbox/tippecanoe/releases/tag/1.4.2).

The bug was that it was trying to remove "unused" movetos after clipping, even though all movetos are significant in points, and then was not guarding against writing out features with empty geometries.

**Comment by tcql** [comment]
:bow: thanks @ericfischer, awesome response tracking that down

**Comment by geohacker** [comment]
Woah, thank you @ericfischer and @tcql! :bow:  :rocket:

**Comment by geohacker** [comment]
I'll test and report.

**Comment by geohacker** [comment]
Works like a charm. Thanks again @tcql and @ericfischer for getting to the bottom of this.
